### ISSUE TITLE
none type error

### ISSUE THREAD

**Issue by arun10797** [HH95/Open-Source-Python-POS-and-Accounting-Software#2]
Traceback (most recent call last):
  File "/home/arush/Desktop/pos/Open-Source-Python-POS-and-Accounting-Software-master/mainInterface.py", line 103, in <module>
    main()
  File "/home/arush/Desktop/pos/Open-Source-Python-POS-and-Accounting-Software-master/mainInterface.py", line 101, in main
    mainInterface(None).Show()
  File "/home/arush/Desktop/pos/Open-Source-Python-POS-and-Accounting-Software-master/mainInterface.py", line 74, in __init__
    self.m_incomeStatementPanel = incomeStatementPanel(self.m_notebook1)
  File "/home/arush/Desktop/pos/Open-Source-Python-POS-and-Accounting-Software-master/incomeStatementPanel.py", line 85, in __init__
    self.populateTable()
  File "/home/arush/Desktop/pos/Open-Source-Python-POS-and-Accounting-Software-master/incomeStatementPanel.py", line 139, in populateTable
    openInv = curs.fetchone()['inventory']
TypeError: 'NoneType' object is not subscriptable
>>>

**Comment by codiumtech** [comment]
Did you find the solution?
